### ISSUE TITLE
下载apk的名称

### ISSUE THREAD

**Issue by lijiam13** [E0HYL/AndrozooDownloader#2]
![图片](https://user-images.githubusercontent.com/72327143/179172998-caa48978-6b92-4012-a43f-13221b55e13f.png)
请问这个下载后的apk名称这样是正常的嘛，如何将名称设置为package name阿

**Comment by E0HYL** [comment]
正常，命名是根据SHA256的。
修改的话调整[download函数](https://github.com/E0HYL/AndrozooDownloader/blob/0435b3852715ff6529af5394fc0cc07003c33471/main.py#L100)write的部分。

**Comment by lijiam13** [comment]
好的，谢谢！
